name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: gcc ./src/main.c -o out
    - name: Package
      run: tar jcf release.tar.bz ./out

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.TOKEN_FOR_TEST }}
        name: ${{ github.ref }}
        files: ./release.tar.bz
        draft: false
