name: Test actions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input test'
        required: true
        default: 'Hello'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get env
      run: |
        echo "$ uname -a"
        uname -a
        echo "$ cat /etc/issue"
        cat /etc/issue
        echo "$ lscpu"
        lscpu
        echo "$ free -h"
        free -h
        echo "$ df -h"
        df -h
        echo "$ ifconfig"
        ifconfig
        echo "$ env"
        env
        echo "$ id"
        id
        echo "$ ls -al"
        ls -al
        
    - uses: actions/checkout@v4

    - name: Build
      run: gcc ./src/main.c -o out

    - name: Docker test
      run: |
        sed -i "s/username/$(id -un)/g" ./run.sh
        sed -i "s/userid/$(id -u)/g" ./run.sh
        sed -i "s/groupname/$(id -gn)/g" ./run.sh
        sed -i "s/groupid/$(id -g)/g" ./run.sh
        chmod +x run.sh
        docker build -t ubuntu_14.04-test:0.1 .
        docker run -itd --name test ubuntu_14.04-test:0.1
        
    - name: Test
      run: ./out # TODO
      
