name: Test actions

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Input test'
        required: true
        default: 'Hello'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get env
      run: |
        echo "$ uname -a"
        uname -a
        echo "$ cat /etc/issue"
        cat /etc/issue
        echo "$ lscpu"
        lscpu
        echo "$ free -h"
        free -h
        echo "$ df -h"
        df -h
        echo "$ ifconfig"
        ifconfig
        echo "$ env"
        env
        echo "$ id"
        id

    - name: Docker test
      run: |
        docker pull busybox
        docker run -it --name test1 busybox /bin/sh
        ps aux
        exit
        docker pull ubuntu:14.04
        
    - uses: actions/checkout@v4

    - name: Build
      run: gcc ./src/main.c -o out

    - name: Test
      run: ./out # TODO
      
